name: Auto-Deploy flk.com.mx

on:
  push:
    branches:
      - main
      - stable

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run FTP Deploy (Bash)
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: bash deploy.sh
